### ISSUE TITLE
Quoted options converted incorrectly

### ISSUE THREAD

**Issue by objectx** [yamadapc/hpack-convert#13]
I've tried to convert a `*.cabal` file contains `ghc-options: -rtsopts "-with-rtsopts=-N -I0 -qg -qb"`.

`hpack-convert` translate it to:

```yaml
ghc-options:
- -rtsopts
- -with-rtsopts=-N -I0 -qg -qb
```

This triggers compilation error.  Quoted options should be handled like [this](https://github.com/sol/hpack/issues/182#issuecomment-310434881 ).

**Comment by yamadapc** [comment]
Fixed to force quoting of multiple word `ghc-options` values.

Gets encoded as:
```yaml
ghc-options:
- ! '"-with-rtsopts=-N -I0 -qg -qb"'
```

Publishing as `v1.0.1` and uploading binaries to releases
