### ISSUE TITLE
Features, improvements wanted?

### ISSUE THREAD

**Issue by ghost** [yamadapc/hpack-convert#6]
I like hpack and I have also been reading through the sources for tools that work with cabal files, so I would like to contribute to the portion of this library that parses cabal files. Any Todo's already on your mind?

**Comment by yamadapc** [comment]
Hey there :)

This library does no cabal file parsing, that's in the `Cabal` package. If you're interested in it, there's a nice to have which would be not to lose any information when parsing/converting (currently it'll lose it on some places; I can't tell of the top of my head, but looking at the AST it'd be +/- clear what it was).

Other than that... I'm not sure if there're things to catch-up on the hpack side; that'd be nice, to par it up with hpack (rebase/merge it, fix conflicts, make sure it works).

And there's one thing I'd like to have which is a YAML/JSON pretty printer that uses a template or some structured way to define field ordering, so the output is nice and the way to output it isn't a hack. This would be useful for several pretty printers; there's a JavaScript library NPM uses that could be used for inspiration.

But all-in-all, I've no requests. This package solves the problem really well for my personal uses. Maybe @sol has ideas.

**Comment by ghost** [comment]
Okay, that should be plenty to start. We'll see how much time I get in on these, then go from there.

Notes: multiple source repo kinds (this, head), some clever way of setting exposed/other modules?, ....

**Comment by ghost** [comment]
> Other than that... I'm not sure if there're things to catch-up on the hpack side; that'd be nice, to par it up with hpack (rebase/merge it, fix conflicts, make sure it works).

Since this is mostly additive, it might be nice to switch to depending on hpack as a library eventually. If it turns out to be a pretty quick effort, I will create a PR for that later.

**Comment by yamadapc** [comment]
The initial project was a PR to hpack, but it is/was a lot of code. The actual diff between our code and the upstream shouldn't be really large, unless I messed-up.

https://github.com/sol/hpack/pull/114

**Comment by sol** [comment]
I think #5 is highest priority (see also https://github.com/sol/hpack/issues/170).

After that, I think rebasing on the latest version of `hpack` and catching up with any changes would be nice  (#5 may actually be solved by that, not sure).

After that, maybe give "using `hpack` as a library" an other shot.

**Comment by yamadapc** [comment]
Sorry about that.

Fixed #5. Going to wait for the travis build to run then publish `v0.14.7`.

As always, it should be buildable from source given the LTS, available as a web service and with binary distributions for OSX and Linux, which is why this didn't seem like a big deal to me.

**Comment by ghost** [comment]
> would be not to lose any information when parsing/converting (currently it'll lose it on some places; I can't tell of the top of my head, but looking at the AST it'd be +/- clear what it was).

Besides multiple source repos, I think you are handling everything currently? I couldn't find anything else that was obviously missing or truncated for Cabal 1.22.

**Comment by ghost** [comment]
Pkgconfig, data-dir have open hpack issues. Could parse them for now... a few more in libinfo. 

Where these intentionally skipped: Test suite - enabled, Benchmark - enabled ?

**Comment by ghost** [comment]
Also, there might be some clever usage of a built in condtree traversal operator to reduce code here.

```

 -- TODO: add wrapper functions that transform top level section 
 --   into specialized section on top of fromCondTree

 fromCondTree :: 
     HasBuildInfo a => Cabal.CondTree Cabal.ConfVar [Cabal.Dependency] a -> Section ()
 fromCondTree ct =
     let x :: Cabal.CondTree String [Cabal.Dependency] (Section ())
         x = 
            Cabal.mapCondTree 
                (sectionWithBuildInfo () . getBuildInfo) 
                id 
                (\cv -> Cabal.Var (fromCondition cv)) ct
         -- TODO: recur once through tree unwrapping from Var, 
         -- and extracting if/else to build Conditional's
     in undefined
 
```

**Comment by ghost** [comment]
You can use that snippet if you have time to refactor later.

That's probably all for now... Long term, maybe Cabal the library can use the skeleton of the logic hpack-convert and hpack use to model the logic for converting existing cabal files into their new front end syntax automatically, and for expanding the front end syntax to the internal syntax.
